# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Project\Python\PocketInstrument\analyzer\va.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys, os

sys.path.append(os.getcwd())
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from PyQt5 import QtCore, QtGui, QtWidgets
from public.public import logSpinBox, doubleSlider


class Myplot(FigureCanvas):
    def __init__(self, parent=None, width=5, height=3, dpi=100):
        # new figure
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        FigureCanvas.__init__(self, self.fig)
        self.setParent(parent)

        d = [0.08, 0.02, 0.02, 0.05]  # left, right, upper, bottom border
        self.ax_A = self.fig.add_axes(
            [d[0], 0.5 + d[3], 1 - d[0] - d[1], 0.5 - d[2] - d[3]]
        )
        self.ax_phi = self.fig.add_axes(
            [d[0], d[3], 1 - d[0] - d[1], 0.5 - d[2] - d[3]]
        )

        # initial figure
        self.compute_initial_figure()

        # size policy
        FigureCanvas.setSizePolicy(
            self, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        FigureCanvas.updateGeometry(self)

    def compute_initial_figure(self):
        pass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.desktop = QtWidgets.QApplication.desktop()

        # 获取显示器分辨率大小
        self.screenRect = self.desktop.screenGeometry()

        # WIDTH = int(0.6 * self.screenRect.width())
        HEIGHT = int(0.8 * self.screenRect.height())
        WIDTH = int(1.235 * HEIGHT)

        rowH = HEIGHT // 16

        winW, winH = HEIGHT, HEIGHT
        sliderD = int(0.035 * HEIGHT)
        measW, measH = WIDTH - HEIGHT - sliderD, rowH * 6
        measX = winW + sliderD
        dispW, dispH = measW, rowH * 4
        fileW, fileH = measW, rowH * 2

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(WIDTH + 30, HEIGHT + int(1.25 * sliderD) + 30)
        # MainWindow.setFont(QtGui.QFont("宋体", 10))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.FigQGB = QtWidgets.QGroupBox(self.centralwidget)
        self.FigQGB.setGeometry(QtCore.QRect(0, 0, winW, winH))
        self.FigQGB.setObjectName("FigQGB")

        self.fig = Myplot(width=5, height=5, dpi=100)

        self.FigGrid = QtWidgets.QGridLayout(self.FigQGB)
        self.FigGrid.setObjectName("FigGrid")
        self.FigGrid.addWidget(self.fig)

        self.VSliderQGB = QtWidgets.QGroupBox(self.centralwidget)
        self.VSliderQGB.setObjectName("VSliderQGB")
        self.VSliderQGB.setGeometry(QtCore.QRect(winW, 0, sliderD, winH))

        self.CursorA = doubleSlider()
        self.CursorA.setOrientation(QtCore.Qt.Vertical)
        self.CursorA.setObjectName("CursorA")

        self.CursorPhi = doubleSlider()
        self.CursorPhi.setOrientation(QtCore.Qt.Vertical)
        self.CursorPhi.setObjectName("CursorPhi")

        self.VSliderGrid = QtWidgets.QVBoxLayout(self.VSliderQGB)
        self.VSliderGrid.setObjectName("VSliderGrid")
        self.VSliderGrid.addWidget(self.CursorA)
        self.VSliderGrid.addWidget(self.CursorPhi)

        self.HSliderQGB = QtWidgets.QGroupBox(self.centralwidget)
        self.HSliderQGB.setObjectName("HSliderQGB")
        self.HSliderQGB.setGeometry(QtCore.QRect(0, winH, winW, int(1.25 * sliderD)))

        self.CursorF = []
        self.CursorF.append(doubleSlider())
        self.CursorF[0].setOrientation(QtCore.Qt.Horizontal)
        self.CursorF[0].setObjectName("CursorF0")
        self.CursorF.append(doubleSlider())
        self.CursorF[1].setOrientation(QtCore.Qt.Horizontal)
        self.CursorF[1].setObjectName("CursorF1")

        self.HSliderGrid = QtWidgets.QVBoxLayout(self.HSliderQGB)
        self.HSliderGrid.setObjectName("HSliderGrid")
        self.HSliderGrid.addWidget(self.CursorF[0])
        self.HSliderGrid.addWidget(self.CursorF[1])

        self.MeasQGB = QtWidgets.QGroupBox(self.centralwidget)
        self.MeasQGB.setObjectName("FuncQGB")
        self.MeasQGB.setGeometry(QtCore.QRect(measX, 0, measW, measH))

        self.ResetButton = QtWidgets.QPushButton()
        self.ResetButton.setObjectName("ResetButton")
        self.ResetButton.setText("Reset")

        self.StartButton = QtWidgets.QPushButton()
        self.StartButton.setObjectName("StartButton")
        self.StartButton.setText("Start")

        self.ScanLabel = QtWidgets.QLabel("扫描类型")
        self.ScanLabel.setObjectName("ScanLabel")

        self.ScanType = QtWidgets.QComboBox()
        self.ScanType.setObjectName("ScanType")
        self.ScanType.addItems(("频段", "频点"))
        self.ScanType.setCurrentIndex(0)

        self.fLeftLabel = QtWidgets.QLabel("f1")
        self.fLeftLabel.setObjectName("fLeftLabel")
        self.fLeft = QtWidgets.QDoubleSpinBox()
        self.fLeft.setObjectName("fLeft")
        self.fLeft.setRange(5, 22050)
        self.fLeft.setSingleStep(100)
        self.fLeft.setValue(1000)

        self.fRightLabel = QtWidgets.QLabel("f2")
        self.fRightLabel.setObjectName("fRightLabel")
        self.fRight = QtWidgets.QDoubleSpinBox()
        self.fRight.setObjectName("fRight")
        self.fRight.setRange(5, 22050)
        self.fRight.setSingleStep(100)
        self.fRight.setValue(2000)

        self.fNumLabel = QtWidgets.QLabel("N")
        self.fNumLabel.setObjectName("fNumLabel")
        self.fNum = QtWidgets.QSpinBox()
        self.fNum.setObjectName("fNum")
        self.fNum.setRange(1, 100)
        self.fNum.setSingleStep(1)
        self.fNum.setValue(5)

        self.fValueLabel = QtWidgets.QLabel("f")
        self.fValueLabel.setObjectName("fValueLabel")
        self.fValue = QtWidgets.QDoubleSpinBox()
        self.fValue.setObjectName("fValue")
        self.fValue.setRange(0, 22050)
        self.fValue.setSingleStep(100)
        # self.fValue.setValue(22050)
        self.fValue.setValue(700)

        self.MeasGrid = QtWidgets.QGridLayout(self.MeasQGB)
        self.MeasGrid.setObjectName("MeasGrid")
        self.MeasGrid.addWidget(self.ResetButton, 0, 0)
        self.MeasGrid.addWidget(self.StartButton, 0, 1)
        self.MeasGrid.addWidget(self.ScanLabel, 1, 0)
        self.MeasGrid.addWidget(self.ScanType, 1, 1)
        self.MeasGrid.addWidget(self.fLeftLabel, 2, 0)
        self.MeasGrid.addWidget(self.fLeft, 2, 1)
        self.MeasGrid.addWidget(self.fRightLabel, 3, 0)
        self.MeasGrid.addWidget(self.fRight, 3, 1)
        self.MeasGrid.addWidget(self.fNumLabel, 4, 0)
        self.MeasGrid.addWidget(self.fNum, 4, 1)
        self.MeasGrid.addWidget(self.fValueLabel, 5, 0)
        self.MeasGrid.addWidget(self.fValue, 5, 1)

        self.DispQGB = QtWidgets.QGroupBox(self.centralwidget)
        self.DispQGB.setObjectName("DispQGB")
        self.DispQGB.setGeometry(QtCore.QRect(measX, measH, dispW, dispH))

        self.fLogCB = QtWidgets.QCheckBox("f log")
        self.fLogCB.setObjectName("fLogCB")
        self.ALogCB = QtWidgets.QCheckBox("A log")
        self.ALogCB.setObjectName("ALogCB")
        self.CursorCB = QtWidgets.QCheckBox("cursor")
        self.CursorCB.setObjectName("CursorCB")
        self.ValueCB = QtWidgets.QCheckBox("value")
        self.ValueCB.setObjectName("ValueCB")

        self.fminLabel = QtWidgets.QLabel("fmin")
        self.fminLabel.setObjectName("fminLabel")
        self.fmin = QtWidgets.QDoubleSpinBox()
        self.fmin.setObjectName("fmin")
        self.fmin.setRange(0, 22050)
        self.fmin.setSingleStep(100)
        self.fmaxLabel = QtWidgets.QLabel("fmax")
        self.fmaxLabel.setObjectName("fmaxLabel")
        self.fmax = QtWidgets.QDoubleSpinBox()
        self.fmax.setObjectName("fmax")
        self.fmax.setRange(0, 22050)
        self.fmax.setValue(0)
        self.fmax.setSingleStep(100)

        self.DispGrid = QtWidgets.QGridLayout(self.DispQGB)
        self.DispGrid.setObjectName("DispGrid")
        self.DispGrid.addWidget(self.fLogCB, 0, 0)
        self.DispGrid.addWidget(self.ALogCB, 0, 1)
        self.DispGrid.addWidget(self.CursorCB, 1, 0)
        self.DispGrid.addWidget(self.ValueCB, 1, 1)
        self.DispGrid.addWidget(self.fminLabel, 2, 0)
        self.DispGrid.addWidget(self.fmin, 2, 1)
        self.DispGrid.addWidget(self.fmaxLabel, 3, 0)
        self.DispGrid.addWidget(self.fmax, 3, 1)

        self.FileQGB = QtWidgets.QGroupBox(self.centralwidget)
        self.FileQGB.setObjectName("FileQGB")
        self.FileQGB.setGeometry(QtCore.QRect(measX, measH + dispH, fileW, fileH))

        self.filename = QtWidgets.QLineEdit()
        self.filename.setObjectName("filename")
        self.dataFormat = QtWidgets.QComboBox()
        self.dataFormat.setObjectName("dataFormat")
        self.dataFormat.addItems((".npy", ".mat", ".txt", ".xlsx"))
        self.dataSave = QtWidgets.QPushButton(text="导出数据")
        self.dataSave.setObjectName("dataSave")
        self.imgFormat = QtWidgets.QComboBox()
        self.imgFormat.setObjectName("imgFormat")
        self.imgFormat.addItems((".png", ".jpg"))
        self.imgSave = QtWidgets.QPushButton(text="保存图片")
        self.imgSave.setObjectName("imgSave")

        self.FileGrid = QtWidgets.QGridLayout(self.FileQGB)
        self.FileGrid.setObjectName("FileGrid")
        self.FileGrid.addWidget(self.filename, 0, 0, 1, 2)
        self.FileGrid.addWidget(self.dataFormat, 1, 0, 1, 1)
        self.FileGrid.addWidget(self.dataSave, 1, 1, 1, 1)
        self.FileGrid.addWidget(self.imgFormat, 2, 0, 1, 1)
        self.FileGrid.addWidget(self.imgSave, 2, 1, 1, 1)

        # self.FuncGrid.addWidget(self.SaveButton, 6, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "波特图仪"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
