# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Project\Python\PocketInstrument\ui\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# import generalFunc as gf


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        width, height = 1200, 600
        itemh = 40
        label_w, label_h = 120, itemh
        input_w, input_h = 160, itemh
        multi_w, multi_h = 80, itemh
        button_w, button_h = 150, itemh
        width1, height1 = 500, 500
        startx, starty = (width - 2 * width1) // 4, (height - height1) // 2
        startx_2 = width // 2 + startx
        col_num = 6
        dy, dx = (height1 - col_num * label_h) // (col_num - 1), (
            width1 - label_w - input_w - multi_w
        ) // 2
        x = [startx, startx + label_w + dx, startx + label_w + input_w + 2 * dx]
        y = [starty + i * (dy + label_h) for i in range(col_num)]
        x_2 = [startx_2, startx_2 + label_w + dx, startx_2 + label_w + input_w + 2 * dx]

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(width, height)
        MainWindow.setFont(QtGui.QFont("宋体", 14))
        MainWindow.setWindowTitle("信号发生器")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        i = 0
        self.channelLabel = QtWidgets.QLabel(self.centralwidget)
        self.channelLabel.setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.channelLabel.setObjectName("channelLabel")
        self.channelLabel.setText("通道1")
        self.switch = QtWidgets.QPushButton(self.centralwidget)
        self.switch.setGeometry(QtCore.QRect(x[1], y[i], button_w, button_h))
        self.switch.setObjectName("switch")
        self.switch.setText("Turn on")
        self.switch.setStyleSheet("background-color: green;")
        i += 1

        self.waveLabel = QtWidgets.QLabel(self.centralwidget)
        self.waveLabel.setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.waveLabel.setObjectName("waveLabel")
        self.waveLabel.setText("波形")
        self.waveSelect = QtWidgets.QComboBox(self.centralwidget)
        self.waveSelect.setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.waveSelect.setObjectName("waveSelect")
        self.waveSelect.addItems(("正弦波", "方波", "锯齿波", "三角波", "直流"))
        i += 1

        self.freqLabel = QtWidgets.QLabel(self.centralwidget)
        self.freqLabel.setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.freqLabel.setObjectName("label")
        self.freqLabel.setText("频率")
        self.freqInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.freqInput.setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.freqInput.setMaximum(20000.0)
        self.freqInput.setObjectName("freqInput")
        self.freqInput.setValue(1000)
        self.freqMultiple = QtWidgets.QComboBox(self.centralwidget)
        self.freqMultiple.setGeometry(QtCore.QRect(x[2], y[i], multi_w, multi_h))
        self.freqMultiple.setObjectName("freqMultiple")
        self.freqMultiple.addItems(("kHz", "Hz"))
        self.freqMultiple.setCurrentIndex(1)
        i += 1

        self.ampLabel = QtWidgets.QLabel(self.centralwidget)
        self.ampLabel.setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.ampLabel.setObjectName("ampLabel")
        self.ampLabel.setText("幅度")
        self.ampInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ampInput.setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.ampInput.setSingleStep(0.1)
        self.ampInput.setObjectName("ampInput")
        self.ampInput.setValue(1)
        self.ampMultiple = QtWidgets.QComboBox(self.centralwidget)
        self.ampMultiple.setGeometry(QtCore.QRect(x[2], y[i], multi_w, multi_h))
        self.ampMultiple.setObjectName("ampMultiple")
        self.ampMultiple.addItems(("V", "mV"))
        i += 1

        self.offsetLabel = QtWidgets.QLabel(self.centralwidget)
        self.offsetLabel.setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.offsetLabel.setObjectName("offsetLabel")
        self.offsetLabel.setText("直流分量")
        self.offsetInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.offsetInput.setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.offsetInput.setSingleStep(0.1)
        self.offsetInput.setObjectName("offsetInput")
        self.offsetInput.setValue(0)
        self.offsetMultiple = QtWidgets.QComboBox(self.centralwidget)
        self.offsetMultiple.setGeometry(QtCore.QRect(x[2], y[i], multi_w, multi_h))
        self.offsetMultiple.setObjectName("offsetMultiple")
        self.offsetMultiple.addItems(("V", "mV"))
        i += 1

        self.dutyLabel = QtWidgets.QLabel(self.centralwidget)
        self.dutyLabel.setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.dutyLabel.setObjectName("dutyLabel")
        self.dutyLabel.setText("占空比")
        self.dutyInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dutyInput.setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.dutyInput.setMaximum(100.0)
        self.dutyInput.setSingleStep(10.0)
        self.dutyInput.setObjectName("dutyInput")
        self.dutyInput.setValue(50)
        self.dutyMultiple = QtWidgets.QComboBox(self.centralwidget)
        self.dutyMultiple.setGeometry(QtCore.QRect(x[2], y[i], multi_w, multi_h))
        self.dutyMultiple.setObjectName("dutyMultiple")
        self.dutyMultiple.addItem("%")
        i += 1

        """
        second column
        """
        i = 0
        self.channelLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.channelLabel_2.setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.channelLabel_2.setObjectName("channelLabel_2")
        self.channelLabel_2.setText("通道2")
        self.switch_2 = QtWidgets.QPushButton(self.centralwidget)
        self.switch_2.setGeometry(QtCore.QRect(x_2[1], y[i], button_w, button_h))
        self.switch_2.setObjectName("switch_2")
        self.switch_2.setText("Turn on")
        self.switch_2.setStyleSheet("background-color: green;")
        i += 1

        self.waveLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.waveLabel_2.setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.waveLabel_2.setObjectName("waveLabel_2")
        self.waveLabel_2.setText("波形")
        self.waveSelect_2 = QtWidgets.QComboBox(self.centralwidget)
        self.waveSelect_2.setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.waveSelect_2.setObjectName("waveSelect_2")
        self.waveSelect_2.addItems(("正弦波", "方波", "锯齿波", "三角波", "直流"))
        i += 1

        self.freqLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.freqLabel_2.setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.freqLabel_2.setObjectName("freqLabel_2")
        self.freqLabel_2.setText("频率")
        self.freqInput_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.freqInput_2.setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.freqInput_2.setMaximum(20000.0)
        self.freqInput_2.setObjectName("freqInput_2")
        self.freqInput_2.setValue(1000)
        self.freqMultiple_2 = QtWidgets.QComboBox(self.centralwidget)
        self.freqMultiple_2.setGeometry(QtCore.QRect(x_2[2], y[i], multi_w, multi_h))
        self.freqMultiple_2.setObjectName("freqMultiple_2")
        self.freqMultiple_2.addItems(("kHz", "Hz"))
        self.freqMultiple_2.setCurrentIndex(1)
        i += 1

        self.ampLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ampLabel_2.setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.ampLabel_2.setObjectName("ampLabel_2")
        self.ampLabel_2.setText("幅度")
        self.ampInput_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ampInput_2.setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.ampInput_2.setSingleStep(0.1)
        self.ampInput_2.setObjectName("ampInput_2")
        self.ampInput_2.setValue(1)
        self.ampMultiple_2 = QtWidgets.QComboBox(self.centralwidget)
        self.ampMultiple_2.setGeometry(QtCore.QRect(x_2[2], y[i], multi_w, multi_h))
        self.ampMultiple_2.setObjectName("ampMultiple_2")
        self.ampMultiple_2.addItems(("V", "mV"))
        i += 1

        self.offsetLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.offsetLabel_2.setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.offsetLabel_2.setObjectName("offsetLabel_2")
        self.offsetLabel_2.setText("直流分量")
        self.offsetInput_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.offsetInput_2.setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.offsetInput_2.setSingleStep(0.1)
        self.offsetInput_2.setObjectName("offsetInput_2")
        self.offsetInput_2.setValue(0)
        self.offsetMultiple_2 = QtWidgets.QComboBox(self.centralwidget)
        self.offsetMultiple_2.setGeometry(QtCore.QRect(x_2[2], y[i], multi_w, multi_h))
        self.offsetMultiple_2.setObjectName("offsetMultiple_2")
        self.offsetMultiple_2.addItems(("V", "mV"))
        i += 1

        self.dutyLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.dutyLabel_2.setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.dutyLabel_2.setObjectName("dutyLabel_2")
        self.dutyLabel_2.setText("占空比")
        self.dutyInput_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dutyInput_2.setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.dutyInput_2.setMaximum(100.0)
        self.dutyInput_2.setSingleStep(10.0)
        self.dutyInput_2.setObjectName("dutyInput_2")
        self.dutyInput_2.setValue(50)
        self.dutyMultiple_2 = QtWidgets.QComboBox(self.centralwidget)
        self.dutyMultiple_2.setGeometry(QtCore.QRect(x_2[2], y[i], multi_w, multi_h))
        self.dutyMultiple_2.setObjectName("dutyMultiple_2")
        self.dutyMultiple_2.addItem("%")
        i += 1

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.var = [
            {
                "switch": self.switch,
                "freqInput": self.freqInput,
                "freqMultiple": self.freqMultiple,
                "ampInput": self.ampInput,
                "ampMultiple": self.ampMultiple,
                "offsetInput": self.offsetInput,
                "offsetMultiple": self.offsetMultiple,
                "dutyInput": self.dutyInput,
            },
            {
                "switch": self.switch_2,
                "freqInput": self.freqInput_2,
                "freqMultiple": self.freqMultiple_2,
                "ampInput": self.ampInput_2,
                "ampMultiple": self.ampMultiple_2,
                "offsetInput": self.offsetInput_2,
                "offsetMultiple": self.offsetMultiple_2,
                "dutyInput": self.dutyInput_2,
            },
        ]
        self.switch.clicked.connect(lambda x: self.on_clicked(0))
        self.switch_2.clicked.connect(lambda x: self.on_clicked(1))

    def on_clicked(self, id):
        if self.var[id]["switch"].text() == "Turn on":
            self.var[id]["switch"].setText("Turn off")
            self.var[id]["switch"].setFont(QtGui.QFont("宋体", 14))
            self.var[id]["switch"].setStyleSheet("background-color: red;")
        else:
            self.var[id]["switch"].setText("Turn on")
            self.var[id]["switch"].setFont(QtGui.QFont("宋体", 14))
            self.var[id]["switch"].setStyleSheet("background-color: green;")

        freq = (
            self.var[id]["freqInput"].value()
            if self.var[id]["freqMultiple"].currentIndex() == 1
            else self.var[id]["freqInput"].value() * 1000
        )
        amp = (
            self.var[id]["ampInput"].value()
            if self.var[id]["ampMultiple"].currentIndex() == 0
            else self.var[id]["ampInput"].value() / 1000
        )
        offset = (
            self.var[id]["offsetInput"].value()
            if self.var[id]["offsetMultiple"].currentIndex() == 0
            else self.var[id]["offsetInput"].value() / 1000
        )
        duty = self.var[id]["dutyInput"].value()
        print([freq, amp, offset, duty])


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
