# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Project\Python\PocketInstrument\analyzer\va.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys, os

sys.path.append(os.getcwd())
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from PyQt5 import QtCore, QtGui, QtWidgets
from public.public import logSpinBox


class Myplot(FigureCanvas):
    def __init__(self, parent=None, width=5, height=3, dpi=100):
        # new figure
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        FigureCanvas.__init__(self, self.fig)
        self.setParent(parent)

        d = 0.05
        self.ax = self.fig.add_axes([d, d, 1 - 2 * d, 1 - 2 * d])

        # initial figure
        self.compute_initial_figure()

        # size policy
        FigureCanvas.setSizePolicy(
            self, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        FigureCanvas.updateGeometry(self)

    def compute_initial_figure(self):
        pass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.desktop = QtWidgets.QApplication.desktop()

        # 获取显示器分辨率大小
        self.screenRect = self.desktop.screenGeometry()

        HEIGHT = int(0.7 * self.screenRect.height())
        WIDTH = HEIGHT + 300

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(WIDTH + 40, HEIGHT + 40)
        MainWindow.setFont(QtGui.QFont("宋体", 14))
        MainWindow.setWindowTitle("时谱图仪")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.FigQGB = QtWidgets.QGroupBox(self.centralwidget)
        self.FigQGB.setGeometry(QtCore.QRect(0, 0, HEIGHT, HEIGHT))
        self.FigQGB.setObjectName("FigQGB")

        self.fig = Myplot(width=5, height=5, dpi=100)

        self.FigGrid = QtWidgets.QGridLayout(self.FigQGB)
        self.FigGrid.setObjectName("FigGrid")
        self.FigGrid.addWidget(self.fig)

        self.FuncQGB = QtWidgets.QGroupBox(self.centralwidget)
        self.FuncQGB.setObjectName("FuncQGB")
        self.FuncQGB.setGeometry(QtCore.QRect(HEIGHT, 0, WIDTH - HEIGHT, 300))

        self.RunButton = QtWidgets.QPushButton()
        self.RunButton.setObjectName("RunButton")

        self.SourceLabel = QtWidgets.QLabel()
        self.SourceLabel.setObjectName("SourceLabel")
        self.SourceLabel.setText("源")
        self.Source = QtWidgets.QComboBox()
        self.Source.setObjectName("Source")
        self.Source.addItems(("1", "2"))

        self.SaveButton = QtWidgets.QPushButton()
        self.SaveButton.setObjectName("SaveButton")
        self.SaveButton.setText("保存图片")

        self.FuncGrid = QtWidgets.QGridLayout(self.FuncQGB)
        self.FuncGrid.setObjectName("FuncGrid")
        self.FuncGrid.addWidget(self.RunButton, 0, 1)
        self.FuncGrid.addWidget(self.SourceLabel, 1, 0)
        self.FuncGrid.addWidget(self.Source, 1, 1)
        self.FuncGrid.addWidget(self.SaveButton, 2, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "示波器"))
        self.RunButton.setText(_translate("MainWindow", "Stop"))
        self.RunButton.setStyleSheet("background-color: red;")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
