# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Project\Python\PocketInstrument\ui\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# import generalFunc as gf


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        width, height = 1200, 900
        itemh = 40
        label_w, label_h = 150, itemh
        input_w, input_h = 300, itemh
        # button_w, button_h = 150, itemh
        disp_w, disp_h = 500, 200
        width1, height1 = 500, 500
        startx, starty = (width - 2 * width1) // 4, (
            height - height1 - disp_h
        ) * 2 // 3 + disp_h
        startx_2 = width // 2 + startx
        row_num = 9
        dy, dx = (height1 - row_num * label_h) // (
            row_num - 1
        ), width1 - label_w - input_w
        x = [startx, startx + label_w + dx, startx + label_w + input_w + 2 * dx]
        y = [starty + i * (dy + label_h) for i in range(row_num)]
        x_2 = [startx_2, startx_2 + label_w + dx, startx_2 + label_w + input_w + 2 * dx]

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(width, height)
        MainWindow.setFont(QtGui.QFont("宋体", 14))
        MainWindow.setWindowTitle("信号发生器")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.QGB0 = QtWidgets.QGroupBox(self.centralwidget)
        self.QGB0.setGeometry(
            QtCore.QRect(startx, (starty - disp_h) // 2, disp_w, disp_h)
        )
        self.QGB0.setObjectName("QGB0")

        self.QGB1 = QtWidgets.QGroupBox(self.centralwidget)
        self.QGB1.setGeometry(
            QtCore.QRect(startx_2, (starty - disp_h) // 2, disp_w, disp_h)
        )
        self.QGB1.setObjectName("QGB1")

        i = 0
        self.synchLabel = QtWidgets.QLabel(self.centralwidget)
        self.synchLabel.setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.synchLabel.setObjectName("synchLabel")
        self.synchLabel.setText("输出方式")
        self.synchSelect = QtWidgets.QComboBox(self.centralwidget)
        self.synchSelect.setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.synchSelect.setObjectName("synchSelect")
        self.synchSelect.addItems(("异步", "同步"))
        self.synchSelect.setCurrentIndex(0)
        i += 1

        self.channelLabel = [
            QtWidgets.QLabel(self.centralwidget),
            QtWidgets.QLabel(self.centralwidget),
        ]
        self.waveSelect = [
            QtWidgets.QComboBox(self.centralwidget),
            QtWidgets.QComboBox(self.centralwidget),
        ]
        self.channelLabel[0].setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.channelLabel[0].setObjectName("channelLabel_0")
        self.channelLabel[0].setText("通道1")
        self.waveSelect[0].setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.waveSelect[0].setObjectName("waveSelect_0")
        self.waveSelect[0].addItems(
            ("关闭", "正弦波", "方波", "直流", "三角波", "锯齿波", "表达式", "文件")
        )
        self.waveSelect[0].setCurrentIndex(0)

        self.channelLabel[1].setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.channelLabel[1].setObjectName("channelLabel_1")
        self.channelLabel[1].setText("通道2")
        self.waveSelect[1].setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.waveSelect[1].setObjectName("waveSelect_1")
        self.waveSelect[1].addItems(
            ("关闭", "正弦波", "方波", "直流", "三角波", "锯齿波", "表达式", "文件")
        )
        self.waveSelect[1].setCurrentIndex(0)
        i += 1

        self.freqLabel = [
            QtWidgets.QLabel(self.centralwidget),
            QtWidgets.QLabel(self.centralwidget),
        ]
        self.freqInput = [
            QtWidgets.QDoubleSpinBox(self.centralwidget),
            QtWidgets.QDoubleSpinBox(self.centralwidget),
        ]
        self.freqLabel[0].setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.freqLabel[0].setObjectName("freqLabel_0")
        self.freqLabel[0].setText("频率/Hz")
        self.freqInput[0].setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.freqInput[0].setMinimum(0.01)
        self.freqInput[0].setMaximum(20000.0)
        self.freqInput[0].setObjectName("freqInput_0")
        self.freqInput[0].setValue(100)

        self.freqLabel[1].setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.freqLabel[1].setObjectName("freqLabel_1")
        self.freqLabel[1].setText("频率/Hz")
        self.freqInput[1].setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.freqInput[1].setMinimum(0.01)
        self.freqInput[1].setMaximum(20000.0)
        self.freqInput[1].setObjectName("freqInput_1")
        self.freqInput[1].setValue(100)
        i += 1

        self.ampLabel = [
            QtWidgets.QLabel(self.centralwidget),
            QtWidgets.QLabel(self.centralwidget),
        ]
        self.ampInput = [
            QtWidgets.QDoubleSpinBox(self.centralwidget),
            QtWidgets.QDoubleSpinBox(self.centralwidget),
        ]
        self.ampLabel[0].setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.ampLabel[0].setObjectName("ampLabel_0")
        self.ampLabel[0].setText("幅度/V")
        self.ampInput[0].setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.ampInput[0].setSingleStep(0.1)
        self.ampInput[0].setObjectName("ampInput_0")
        self.ampInput[0].setValue(5)

        self.ampLabel[1].setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.ampLabel[1].setObjectName("ampLabel_1")
        self.ampLabel[1].setText("幅度/V")
        self.ampInput[1].setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.ampInput[1].setSingleStep(0.1)
        self.ampInput[1].setObjectName("ampInput_1")
        self.ampInput[1].setValue(5)
        i += 1

        self.offsetLabel = [
            QtWidgets.QLabel(self.centralwidget),
            QtWidgets.QLabel(self.centralwidget),
        ]
        self.offsetInput = [
            QtWidgets.QDoubleSpinBox(self.centralwidget),
            QtWidgets.QDoubleSpinBox(self.centralwidget),
        ]
        self.offsetLabel[0].setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.offsetLabel[0].setObjectName("offsetLabel_0")
        self.offsetLabel[0].setText("偏置/V")
        self.offsetInput[0].setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.offsetInput[0].setSingleStep(0.1)
        self.offsetInput[0].setObjectName("offsetInput_0")
        self.offsetInput[0].setValue(0)
        self.offsetInput[0].setRange(-10, 10)

        self.offsetLabel[1].setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.offsetLabel[1].setObjectName("offsetLabel_1")
        self.offsetLabel[1].setText("偏置/V")
        self.offsetInput[1].setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.offsetInput[1].setSingleStep(0.1)
        self.offsetInput[1].setObjectName("offsetInput_1")
        self.offsetInput[1].setValue(0)
        self.offsetInput[1].setRange(-10, 10)
        i += 1

        self.dutyLabel = [
            QtWidgets.QLabel(self.centralwidget),
            QtWidgets.QLabel(self.centralwidget),
        ]
        self.dutyInput = [
            QtWidgets.QDoubleSpinBox(self.centralwidget),
            QtWidgets.QDoubleSpinBox(self.centralwidget),
        ]
        self.dutyLabel[0].setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.dutyLabel[0].setObjectName("dutyLabel_0")
        self.dutyLabel[0].setText("占空比/%")
        self.dutyInput[0].setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.dutyInput[0].setMaximum(100.0)
        self.dutyInput[0].setSingleStep(10.0)
        self.dutyInput[0].setObjectName("dutyInput_0")
        self.dutyInput[0].setValue(50)

        self.dutyLabel[1].setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.dutyLabel[1].setObjectName("dutyLabel_1")
        self.dutyLabel[1].setText("占空比/%")
        self.dutyInput[1].setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.dutyInput[1].setMaximum(100.0)
        self.dutyInput[1].setSingleStep(10.0)
        self.dutyInput[1].setObjectName("dutyInput_1")
        self.dutyInput[1].setValue(50)
        i += 1

        self.phiLabel = [
            QtWidgets.QLabel(self.centralwidget),
            QtWidgets.QLabel(self.centralwidget),
        ]
        self.phiInput = [
            QtWidgets.QDoubleSpinBox(self.centralwidget),
            QtWidgets.QDoubleSpinBox(self.centralwidget),
        ]
        self.phiLabel[0].setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.phiLabel[0].setObjectName("phiLabel_0")
        self.phiLabel[0].setText("相位/°")
        self.phiInput[0].setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.phiInput[0].setMaximum(360.0)
        self.phiInput[0].setSingleStep(10)
        self.phiInput[0].setObjectName("phiInput_0")
        self.phiInput[0].setValue(0)

        self.phiLabel[1].setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.phiLabel[1].setObjectName("phiLabel_1")
        self.phiLabel[1].setText("相位/°")
        self.phiInput[1].setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.phiInput[1].setMaximum(360.0)
        self.phiInput[1].setSingleStep(10)
        self.phiInput[1].setObjectName("phiInput_1")
        self.phiInput[1].setValue(0)
        i += 1

        self.expLabel = [
            QtWidgets.QLabel(self.centralwidget),
            QtWidgets.QLabel(self.centralwidget),
        ]
        self.expInput = [
            QtWidgets.QLineEdit(self.centralwidget),
            QtWidgets.QLineEdit(self.centralwidget),
        ]
        self.expLabel[0].setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.expLabel[0].setObjectName("expLabel_0")
        self.expLabel[0].setText("表达式")
        self.expInput[0].setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.expInput[0].setObjectName("expInput_0")
        self.expInput[0].setText("0,1;sin(100*t)")

        self.expLabel[1].setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.expLabel[1].setObjectName("expLabel_1")
        self.expLabel[1].setText("表达式")
        self.expLabel[1].adjustSize()
        self.expInput[1].setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.expInput[1].setObjectName("expInput_1")
        self.expInput[1].setText("0,1;sin(100*t)")
        i += 1

        self.fileLabel = [
            QtWidgets.QLabel(self.centralwidget),
            QtWidgets.QLabel(self.centralwidget),
        ]
        self.fileInput = [
            QtWidgets.QLineEdit(self.centralwidget),
            QtWidgets.QLineEdit(self.centralwidget),
        ]
        self.fileLabel[0].setGeometry(QtCore.QRect(x[0], y[i], label_w, label_h))
        self.fileLabel[0].setObjectName("fileLabel_0")
        self.fileLabel[0].setText("文件名")
        self.fileInput[0].setGeometry(QtCore.QRect(x[1], y[i], input_w, input_h))
        self.fileInput[0].setObjectName("fileInput_0")

        self.fileLabel[1].setGeometry(QtCore.QRect(x_2[0], y[i], label_w, label_h))
        self.fileLabel[1].setObjectName("fileLabel_1")
        self.fileLabel[1].setText("文件名")
        self.fileInput[1].setGeometry(QtCore.QRect(x_2[1], y[i], input_w, input_h))
        self.fileInput[1].setObjectName("fileInput_1")
        i += 1

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
